version: "3.0"

services:
  load-balancer:
    build: load-balancer
    ports:
      - "9000:9000"
    volumes: 
      - ./load-balancer/load-balancer.js:/app/load-balancer.js
  app1:
    build: app
    links:
      - db
    volumes: 
      - ./app/app.js:/app/app.js
  app2:
    build: app
    links:
      - db
    volumes: 
      - ./app/app.js:/app/app.js
  app3:
    build: app
    links:
      - db
    volumes: 
      - ./app/app.js:/app/app.js
  db: 
    build: db
    volumes: 
      - ./data.json:/app/data.json
